language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    # workaround for travis ignoring system_site_packages in travis.yml
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  # For pytables
  - sudo apt-get install libhdf5-serial-dev hdf5-tools python-numexpr cython
  # For numpy/scipy
  - sudo apt-get install -qq gfortran swig liblapack-dev
  - sudo apt-get install -qq libatlas-base-dev libjpeg-dev libhdf5-serial-dev
  - sudo apt-get install -qq liblzo2-dev libsuitesparse-dev
  # For matplotlib
  - sudo apt-get install -qq libpng12-dev libfreetype6-dev tk-dev
  - sudo apt-get install python-numpy
  - sudo apt-get install python-scipy
  - sudo apt-get install python-matplotlib
   #For Opencv
  #- sudo apt-get install opencv
#  - mkdir ./opencv
#  - cd ./opencv
#  - wget ftp://ftp.videolan.org/pub/videolan/x264/snapshots/last_stable_x264.tar.bz2
#  - tar xjf last_stable_x264.tar.bz2
#  - cd last_stable_x264
#  - ./configure --enable-static && make && sudo make install
#  - cd ..
#  - wget http://ffmpeg.org/releases/ffmpeg-0.11.1.tar.gz
#  - tar xzf ffmpeg-0.11.1.tar.gz
#  - cd ffmpeg-0.11.1
#  - ./configure --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-nonfree --enable-postproc --enable-version3 --enable-x11grab && make && sudo make install
#  - cd ..
#  - wget http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.1/OpenCV-2.4.1.tar.bz2
#  - tar xjf OpenCV-2.4.1.tar.bz2
#  - cd OpenCV-2.4.1
#  - mkdir release
#  - cd release
#  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_PYTHON_SUPPORT=ON -D BUILD_EXAMPLES=ON .. && make && sudo make install
#  - cd ../../..
  - sudo apt-get install python-opencv
  # For PySide
  - sudo apt-get install python-pyside
  # For testing
  - sudo apt-get install python-nose

install:
  #- "pip install -r requirements.txt --use-mirrors"
  - "pip install pypubsub"
  - "pip install tables"

script: nosetests