language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
    # workaround for travis ignoring system_site_packages in travis.yml
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo add-apt-repository ppa:pyside --yes
  - sudo apt-get update -qq
  # For PySide
  - sudo apt-get install python-pyside
  - sudo apt-get install python-qt4
  # For pytables
  - sudo apt-get install -qq libhdf5-serial-dev hdf5-tools python-numexpr cython
  # For numpy/scipy
  - sudo apt-get install -qq gfortran swig liblapack-dev
  - sudo apt-get install -qq libatlas-base-dev libjpeg-dev libhdf5-serial-dev
  - sudo apt-get install -qq liblzo2-dev libsuitesparse-dev
  # For matplotlib
  - sudo apt-get install -qq libpng12-dev libfreetype6-dev tk-dev
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python-scipy
  - sudo apt-get install -qq python-matplotlib
   #For OpenCV
  - sudo apt-get install python-opencv
  # For testing
  - sudo apt-get install python-nose

install:
  - "pip install -q pypubsub --use-mirrors"
  - "pip install -q numexpr==1.4.2 --use-mirrors"
  - "pip install -q cython --use-mirrors"
  - "pip install -q tables==2.4.0 --use-mirrors"

script: nosetests