language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    # workaround for travis ignoring system_site_packages in travis.yml
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get update
  # For pytables
  - sudo apt-get install libhdf5-serial-dev hdf5-tools python-numexpr cython
  # For numpy/scipy
  - sudo apt-get install -qq gfortran swig liblapack-dev
  - sudo apt-get install -qq libatlas-base-dev libjpeg-dev libhdf5-serial-dev
  - sudo apt-get install -qq liblzo2-dev libsuitesparse-dev
  # For matplotlib
  - sudo apt-get install -qq libpng12-dev libfreetype6-dev tk-dev
  - sudo apt-get install python-numpy
  - sudo apt-get install python-scipy
  - sudo apt-get install python-matplotlib
   #For Opencv
  #- sudo apt-get install opencv
  - sudo apt-get install python-opencv
  # For PySide
  #- sudo apt-get install python-pyside
  # For testing
  - sudo apt-get install python-nose

install:
  #- "pip install -r requirements.txt --use-mirrors"
  - "pip install pypubsub"
  - "pip install tables"

script: nosetests