language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq install python-numpy python-scipy python-opencv
  - sudo apt-get -qq install libhdf5-serial-dev hdf5-tools

install:
  - "pip install -r requirements.txt --use-mirrors"

script: nosetests
