language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    # workaround for travis ignoring system_site_packages in travis.yml
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo add-apt-repository ppa:pyside
  - sudo apt-get update -qq
  # For PySide
  - sudo apt-get install qt-sdk
  - sudo apt-get install cmake
  - git clone https://github.com/PySide/pyside-setup.git pyside-setup
  - cd pyside-setup
  - python2.7 setup.py bdist_egg --version=1.2.1
  - sudo easy_install-2.7 dist/PySide-1.2.1-py2.7.egg
  - sudo python2.7 pyside_postinstall.py -install
  #- sudo apt-get install python-pyside
  # For pytables
  - sudo apt-get install -qq libhdf5-serial-dev hdf5-tools python-numexpr cython
  # For numpy/scipy
  - sudo apt-get install -qq gfortran swig liblapack-dev
  - sudo apt-get install -qq libatlas-base-dev libjpeg-dev libhdf5-serial-dev
  - sudo apt-get install -qq liblzo2-dev libsuitesparse-dev
  # For matplotlib
  - sudo apt-get install -qq libpng12-dev libfreetype6-dev tk-dev
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python-scipy
  - sudo apt-get install -qq python-matplotlib
   #For Opencv
  #- sudo apt-get install opencv
  - sudo apt-get install python-opencv
  # For testing
  - sudo apt-get install python-nose

install:
  #- "pip install -r requirements.txt --use-mirrors"
  - "pip install -q pypubsub --use-mirrors"
  - "pip install -q numexpr==1.4.2 --use-mirrors"
  - "pip install -q cython --use-mirrors"
  - "pip install -q tables==2.4.0 --use-mirrors"
  - "pip install -q yaml --use-mirrors"

script: nosetests