name: pawlabeling
channels:
  - clinicalgraphics
  - ivoflipse
  - menpo
dependencies:
  - python =2.7*
  - opencv =2.4*
  - pyside =1.2*
  - numpy =1.11*
  - scipy =0.17*
  - pytables =3.2*
  - pypubsub =3.3.0
  - matplotlib =1.5*
  - pandas =0.18*
  - future =0.15*
  # dev
  - anaconda-client >=1.2.1,<1.3
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  - requests =2.9*
  # tests
  - pytest =2.9*
  - mock =1.3*
  - pytest-mock =0.10*
  - pytest-cov =2.2.1
  - pytest-xdist =1.14
  # docs
  - sphinx >=1.3.1,<1.4
  - numpydoc =0.6*