package:
  name: pawlabeling
  version: 0.3.0
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
requirements:
  build:
    - python 2.7*
    - opencv 2.4*
    - pyside 1.2*
    - numpy 1.10*
    - scipy 0.17*
    - pytables 3.2*
    - pypubsub 3.3.0
    - matplotlib 1.5*
    - pandas 0.18*
    - future 0.15*
    - pyyaml 3.11*
  run:
    - python 2.7*
    - opencv 2.4*
    - pyside 1.2*
    - numpy 1.10*
    - scipy 0.17*
    - pytables 3.2*
    - pypubsub 3.3.0
    - matplotlib 1.5*
    - pandas 0.18*
    - future 0.15*
    - pyyaml 3.11*
source:
  path: ..
test:
  commands:
    - py.test -n2 --pyargs pawlabeling
  imports:
    - pawlabeling
  requires:
    - pytest 2.9*
    - mock 1.3*
    - pytest-mock 0.10*
    - pytest-cov 2.2.1
    - pytest-xdist 1.14
about:
  home: https://github.com/ivoflipse/Pawlabeling
  license: BSD 2-Clause
  summary: Clinical Graphics' scientific toolkit