folders:
  measurement_folder: .\samples\Measurements
  store_results_folder: .\samples\Labels
interpolation_degree:
  entire_plate: 4
  paws_widget: 8
  results: 16
sensors:
  height: 1
  width: 1
thresholds:
  end_force_percentage: 0.25
  padding_factor: 1
  start_force_percentage: 0.25
  tracking_spatial: 1.25
  tracking_surface: 0.25
  tracking_temporal: 0.5
widgets:
  entire_plate_widget_height: 450
  entire_plate_widget_width: 800
  main_window_height: 830
  main_window_left: 0
  main_window_top: 25
  main_window_width: 1440
  paws_widget_height: 170
