folders:
  measurement_folder: ".\\samples\\Measurements"
  store_results_folder: ".\\samples\\Labels"

plate:
  brand: "rsscan"
  model: "2m 2nd gen"
  frequency: 125

sensors:
  width: 1
  height: 1

widgets:
  main_window_left: 0
  main_window_top: 25
  main_window_width: 1440
  main_window_height: 830
  entire_plate_widget_width: 800
  entire_plate_widget_height: 450
  contacts_widget_height: 170

interpolation_degree:
  entire_plate: 4
  contacts_widget: 8
  results: 16

thresholds:
  start_force_percentage: 0.25
  end_force_percentage: 0.25
  tracking_temporal: 0.5
  tracking_spatial: 1.25
  tracking_surface: 0.25
  padding_factor: 1

application:
  zip_files: True