application:
  show_maximized: true
  zip_files: true
database:
  database_file: C:\Dropbox\Development\Pawlabeling\pawlabeling\database\data.h5
  database_folder: .\database
folders:
  measurement_folder: C:\Dropbox\Development\Pawlabeling\pawlabeling\samples\Measurements
  store_results_folder: .\samples\Labels
interpolation_degree:
  interpolation_contact_widgets: 8
  interpolation_entire_plate: 4
  interpolation_results: 16
plate:
  brand: rsscan
  frequency: 125
  model: 2m 2nd gen
sensors:
  height: 1
  width: 1
shortcuts:
  invalid_contact: Delete
  left_front: '7'
  left_hind: '1'
  next_contact: '6'
  previous_contact: '4'
  remove_label: '5'
  right_front: '9'
  right_hind: '3'
thresholds:
  end_force_percentage: 0.25
  padding_factor: 1
  start_force_percentage: 0.25
  tracking_spatial: 1.25
  tracking_surface: 0.25
  tracking_temporal: 0.5
widgets:
  contacts_widget_height: 170
  entire_plate_widget_height: 450
  entire_plate_widget_width: 800
  main_window_height: 830
  main_window_left: 0
  main_window_top: 25
  main_window_width: 1440
